version: "3.5"
services:
  app:
    image: python:latest
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0:8000"
    container_name: "${APP_CONTAINER}"
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: "${APP_CONTAINER}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - "${APP_VOLUME}"
    working_dir: "${APP_WORKING_DIR}"
networks:
  default:
    name: "${NETWORK}"